 repos:
      - repo: https://github.com/ambv/black
        rev: 24.8.0
        hooks:
          - id: black
            types: [python]
            language_version: python3.12

      - repo: https://github.com/pycqa/flake8
        rev: 7.1.1
        hooks:
        - id: flake8
          types: [python]
      
      - repo: https://github.com/pycqa/isort
        rev: 5.13.2
        hooks:
          - id: isort
      

      